#!/bin/bash 
rm floppy.img
rm test.o
rm test.bin
rm test.elf
gcc -std=c99 -c -g -march=i686 -m32 -ffreestanding -Wall -Werror test.c -o test.o
ld -static -Ttest.ld -m elf_i386 -nostdlib --nmagic -o test.elf test.o
objcopy -O binary test.elf test.bin
dd if=test.bin of=floppy.img
cp floppy.img KERNEL.BIN
